### ISSUE TITLE
Options to change default allotment time (and for which period of the day)

### ISSUE THREAD

**Issue by xynyx** [LHL-FocusPocus/FocusPocus#48]

**Comment by jpqy** [comment]
I think rather than having the user manually type out what quota they want on each day, we eventually let them specify a starting quota (ex. 2h), ending quota (ex. 1h), and the amount to decrement by each day. (ex. 5 min). The server route would then take care of the setting of quota in db. i.e today: 2h, tomorrow: 1:55...

But for now I think just a single input to set their quota and keep it constant would be a good start, rather than complicating things with lots of input fields that we will remove later anyway.

**Comment by xynyx** [comment]
Sounds good, will just start with the very basics with a static quota they set.
